### ISSUE TITLE
1.21 broke chromedriver support

### ISSUE THREAD

**Issue by coolo** [teodesian/Selenium-Remote-Driver#364] opened 2018-01-29 15:31 UTC
Hi,

Since we updated to 1.21 I get this in my tests using chromedriver:

Uncaught exception from user code:
        Error while executing command: Server returned error message unknown command: session/8372c046bd9cba3aa5ac71062c685836/window/rect instead of data at /suse/coolo/perl5/lib/perl5/Selenium/Remote/Driver.pm line 378.
         at /suse/coolo/perl5/lib/perl5/Selenium/Remote/Driver.pm line 344.

This is 100% reproducible and a git bisect lead me to 3f6169175521acde6130e80ac0431de96089185b. This happens both in my perl 5.26 work station as on the perl 5.18 travis builds we do. E.g. 
https://travis-ci.org/os-autoinst/openQA/jobs/333771338

**Comment by teodesian** [comment] 2018-01-29 15:54
Try 1.22, It should be fixed there.

**Comment by teodesian** [comment] 2018-01-29 15:59
In any case, steps to reproduce would be appreciated.

**Comment by teodesian** [comment] 2018-01-29 16:21
This likely means that chromedriver identifies itself the exact same way in pre-WD3 drivers as it does currently, which honestly isn't much of a shock now that I've been dealing with this.  The fix would probably be to torture the driver until it confess()es that it isn't really WD3 capable at all.

**Comment by teodesian** [comment] 2018-01-29 16:41
Try above patch, I've disabled using WD3 set/get window rect on chrome with a hammer, and it seems to work fine on latest chrome/chromedriver.

**Comment by teodesian** [comment] 2018-01-29 16:44
Oh, you can always try the 'nuclear option' and just do $driver->{is_wd3} = 0 to force all interaction to be done by JSONWire methods.

**Comment by coolo** [comment] 2018-01-29 17:21
this is stable chrome on travis and chromium 63 on my workstation - both show exactly the same error.

The patch worked for me, but I had to disable the tests to convince dist::zilla to install :)

And the code crashing isn't doing anything fancy:

From https://github.com/os-autoinst/openQA/blob/master/t/lib/OpenQA/SeleniumTest.pm

```
        $_driver = Test::Selenium::Chrome->new(%opts);
        $_driver->set_implicit_wait_timeout(2000);
        $_driver->set_window_size(600, 800);
        $_driver->get("http://localhost:$mojoport/");
```

**Comment by teodesian** [comment] 2018-01-29 17:25
Cool, looks like I figured it out then.  OK, I'll get the unit tests' attitude adjusted, and will submit a new version to CPAN tonight.  Thanks for the report.

**Closed** 2018-01-29 19:06 UTC
Labels: bug
