### ISSUE TITLE
Unable to find a matching set of capabilities with Firefox

### ISSUE THREAD

**Issue by ylavoie** [teodesian/Selenium-Remote-Driver#375] opened 2018-03-06 18:43 UTC
Using S::R::D 1.25+, Geckodriver 1.19.1 and Firefox 57.0.4, the only way I was able to get a connection was to remove the `platform => 'ANY'` in the Driver->new.
It is documented that there is a problem in newer Selenium versions with platform negociation.
I suggest to remove it when FORCE_WD3 is effective for Firefox.

**Comment by teodesian** [comment] 2018-03-06 21:54
Is this when using Selenium::Firefox or S::R::D?  I can figure it out if you don't tell me but you could save me some time by letting me know.

**Comment by ylavoie** [comment] 2018-03-07 03:13
Sorry. I used Selenium::Firefox like this:
```
    require Selenium::Firefox::Profile;
    my $caps = {
        extra_capabilities => {
            'moz:firefoxOptions' => {
              args    => [ '-headless' ],
            },
        },
    };
    $Selenium::Remote::Driver::FORCE_WD3 = 1;
    $driver = Selenium::Firefox->new(%{$caps});
```

**Comment by teodesian** [comment] 2018-03-07 05:08
Thanks.  I'll look at a fix for this tomorrow morning.

**Comment by teodesian** [comment] 2018-03-25 03:07
I think @ylavoie's patch fixes this -- I'm going to test and close out tomorrow morning.

**Comment by teodesian** [comment] 2018-03-25 16:57
Without your code I merged, I cannot reproduce the problem with your provided script.  Perhaps there was something else going on?

**Comment by teodesian** [comment] 2018-08-17 22:27
This should be fixed in #396, we now forcibly erase the platform, version and browser name from the caps passed.

**Closed by teodesian** 2018-08-17 22:27 UTC
Labels: bug, needs: reporter input
