### ISSUE TITLE
Checkboxes detach elements - change from 1.26 to 1.27.

### ISSUE THREAD

**Issue by DrJHD** [teodesian/Selenium-Remote-Driver#387] opened 2018-05-29 15:14 UTC
use strict; use warnings;
    use Test::More;
    use Selenium::Chrome;

    my $url    = 'https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_checked';
    my $driver = Selenium::Chrome->new();
    $driver->get($url);
    my $frame = $driver->find_element(
        qw{//iframe[@name='iframeResult']});
    $driver->switch_to_frame($frame);
    $driver->find_element(
        q<//input[@value='Bike']>)->click;
    $driver->find_element(
        q<//input[@value='Submit']>)->click;
    $frame = $driver->find_element(
        qw{//iframe[@name='iframeResult']});
    $driver->switch_to_frame($frame);
    my $elt = $driver->find_element(
        "//body[\@class='w3-container']/div");
    is $elt->get_text(),
        'vehicle=Bike&vehicle=Car ',
        'Both boxes selected';
    $driver->quit();
    done_testing;

This worked in 1.26. In 1.27, a "no such element" error is returned. All elements appear to be "detached" from the browser. The radio button equivalent works under both versions.

**Comment by teodesian** [comment] 2018-06-05 13:29
is the detachment croak thrown during:
`is $elt->get_text(),`
`    'vehicle=Bike&vehicle=Car ',`
`    'Both boxes selected';`

?

**Comment by teodesian** [comment] 2018-06-05 13:37
On Ubuntu  16.04, Using chromedriver 2.39, chromium-browser 66.0.3359.181, with chromedriver in CWD and test script above named test.pl (also added in a $driver->debug_on(1) after instantiation):

prove -vm -Ilib test.pl
test.pl .. 
Prepping findElement
Executing findElement
REQ: POST, http://127.0.0.1:9515/wd/hub/session/a7e14526a363ea01c5be8c9d35fa4814/element, {"using":"xpath","value":"//iframe[@name='iframeResult']"}
RES: {"sessionId":"a7e14526a363ea01c5be8c9d35fa4814","status":0,"value":{"ELEMENT":"0.13981912989346612-1"}}

Prepping switchToFrame
Executing switchToFrame
REQ: POST, http://127.0.0.1:9515/wd/hub/session/a7e14526a363ea01c5be8c9d35fa4814/frame, {"id":{"ELEMENT":"0.13981912989346612-1"}}
RES: {"sessionId":"a7e14526a363ea01c5be8c9d35fa4814","status":0,"value":null}

Prepping findElement
Executing findElement
REQ: POST, http://127.0.0.1:9515/wd/hub/session/a7e14526a363ea01c5be8c9d35fa4814/element, {"value":"//input[@value='Bike']","using":"xpath"}
RES: {"sessionId":"a7e14526a363ea01c5be8c9d35fa4814","status":0,"value":{"ELEMENT":"0.5488334535218966-1"}}

Prepping clickElement
Executing clickElement
REQ: POST, http://127.0.0.1:9515/wd/hub/session/a7e14526a363ea01c5be8c9d35fa4814/element/0.5488334535218966-1/click, {}
RES: {"sessionId":"a7e14526a363ea01c5be8c9d35fa4814","status":11,"value":{"message":"element not visible\n  (Session info: chrome=66.0.3359.181)\n  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.4.0-127-generic x86_64)"}}

Error while executing command: element not visible
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.4.0-127-generic x86_64) at /home/doge/Code/Selenium-Remote-Driver/lib/Selenium/Remote/Driver.pm line 843.
 at /home/doge/Code/Selenium-Remote-Driver/lib/Selenium/Remote/Driver.pm line 800.
Prepping quit
Executing quit
REQ: DELETE, http://127.0.0.1:9515/wd/hub/session/a7e14526a363ea01c5be8c9d35fa4814, {}
RES: {"sessionId":"a7e14526a363ea01c5be8c9d35fa4814","status":0,"value":null}

Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 

Test Summary Report
-------------------
test.pl (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  3 wallclock secs ( 0.01 usr  0.00 sys +  0.14 cusr  0.02 csys =  0.17 CPU)
Result: FAIL

Cannot reproduce.  Is there something more specific that works?

**Comment by teodesian** [comment] 2018-06-05 13:40
Ah, problem is you omitted a window resize; the default window size on some installations is 0px by 0px.  That gets me to an 'iframe not found' error:

Prepping findElement
Executing findElement
REQ: POST, http://127.0.0.1:9515/wd/hub/session/6310edc1301151e034f0cba9461568a7/element, {"value":"//iframe[@name='iframeResult']","using":"xpath"}
RES: {"sessionId":"6310edc1301151e034f0cba9461568a7","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//iframe[@name='iframeResult']\"}\n  (Session info: chrome=66.0.3359.181)\n  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.4.0-127-generic x86_64)"}}

Error while executing command: no such element: Unable to locate element: {"method":"xpath","selector":"//iframe[@name='iframeResult']"}
  (Session info: chrome=66.0.3359.181)

**Comment by teodesian** [comment] 2018-06-05 13:48
Ok, you omitted a switch back to the parent frame in your example, which caused the iframe to not be selected  A short wait to allow page ready was also required.  Fixed script which passes:

use strict; use warnings;
use Test::More;
use Selenium::Chrome;

my $url    = 'https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_checked';
my $driver = Selenium::Chrome->new();
$driver->set_window_size(640,480);
$driver->get($url);
$driver->debug_on(1);
my $frame = $driver->find_element(
    qw{//iframe[@name='iframeResult']});
$driver->switch_to_frame($frame);
$driver->find_element(
    q<//input[@value='Bike']>)->click;
$driver->find_element(
    q<//input[@value='Submit']>)->click;
$driver->switch_to_frame();

sleep 5;
$frame = $driver->find_element(
    qw{//iframe[@name='iframeResult']});
$driver->switch_to_frame($frame);
my $elt = $driver->find_element(
    "//body[\@class='w3-container']/div");
is $elt->get_text(),
    'vehicle=Bike&vehicle=Car ',
    'Both boxes selected';
$driver->quit();
done_testing;

So yeah, cannot reproduce without additional details.

**Comment by teodesian** [comment] 2018-08-17 22:29
closing this as  I cannot reproduce it and have no reporter input after months.

**Closed by teodesian** 2018-08-17 22:29 UTC
Labels: needs: reporter input
